/* GENERATED by scripts/build-email-concepts.ts. Do not edit.
   Source: src/server/modules/email/concepts/*.html */

export const emailConcepts = [
  {
    id: 'concept-a-editorial',
    title: "Mermade Market: applications are open for November",
    html: `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- Many clients invert. Every text cell below carries its own bgcolor as well,
     so nothing is dark ink on a transparent ground if a client ignores this. -->
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>Mermade Market: applications are open for November</title>

<!--
  ══════════════════════════════════════════════════════════════════════
  DIRECTION A · EDITORIAL
  One photograph opens the page. The type stays quiet and precise around
  it. One accent (the gold, #bc9658), one button style, used twice.

  TOKENS, from docs/08-DESIGN-SYSTEM.md §2 and src/server/modules/email/shell.ts
    GOLD  #bc9658   accent: eyebrows only
    INK   #171717   headings, dates, the button ground
    BODY  #5c5c5c   prose
    RULE  #dfe3e8   hairlines
    PAPER #ffffff   the paper
    SHELL #f6f7f7   the ground the paper sits on, and the colophon
    MUTED #767676   small print, 4.6:1 on white

  TYPE, AND WHAT HAPPENS IN GMAIL
  Oswald and Figtree load in Apple Mail, iOS Mail and Samsung Mail. Gmail
  strips the <link> and falls back. So the sizes below are chosen to hold
  in the fallback, and no role depends on the webfont arriving:

    Display line  Figtree 600 · 36/1.06 · sentence case
                  fallback: -apple-system, BlinkMacSystemFont, 'Segoe UI',
                  Roboto, Helvetica, Arial, sans-serif
                  Deliberately NOT Oswald. Drew: "I do not like all caps
                  headers unless they use our fonts." A 36px Oswald headline
                  becomes 36px of Helvetica capitals in Gmail, which is not
                  this brand at any size. Figtree's fallbacks are ordinary
                  grotesques of a similar x-height, so the line degrades to
                  something close instead of to something else.

    Standfirst    Figtree 400 · 18/1.55 · same stack. Holds in Helvetica.
    Prose         Figtree 400 · 16.5/1.68 at a 512px measure, ~60 characters.
    Timetable     dates in Oswald 600 caps 13px; if Oswald is missing,
                  'Arial Narrow' then Helvetica. The column is 118px wide,
                  which fits "NOV 13-15" in Helvetica caps at 13px with room
                  to spare, so the table never reflows.
    Labels        Oswald 600 · 12px · .18em tracked caps. At 12px, tracked
                  and short, a fallback grotesque still reads as a label.
                  Nothing tracked goes below 12px (design system §1).
    Button        Oswald 700 · 15px · .09em tracked caps, white on ink.
                  In the fallback it is tracked Helvetica caps on black,
                  which is still unmistakably a button.

  IMAGES
  Three photographs, all real files in public/photos, all with width
  attributes, alt text and display:block. Nothing meaningful is a
  background-image. If images are blocked the email still reads: the
  masthead falls back to its alt text, and the facts are all live text.
  ══════════════════════════════════════════════════════════════════════
-->

<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=Figtree:wght@400;500;600&display=swap" rel="stylesheet">

<style>
  /* Phones only, and only in clients that read a media query. Nothing here
     is load-bearing: the layout is tables and widths, and it is correct
     without a single one of these rules. This only stops the display line
     from taking four lines on a 320px screen and pulls the generous
     editorial margins in to something a thumb-width page can afford. */
  @media only screen and (max-width:480px) {
    .mm-display { font-size:29px !important; line-height:1.1 !important; }
    .mm-stand   { font-size:17px !important; }
    .mm-pad     { padding-left:24px !important; padding-right:24px !important; }
    .mm-date    { font-size:12px !important; }
  }
</style>
</head>

<body style="margin:0;padding:0;background:#f6f7f7;">

<!-- Preheader. The line the inbox shows next to the subject, then enough
     blanks that it does not go on to read the masthead out loud. -->
<div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">Applications close September 21 at 11:59pm PT. One form covers both tracks, and we answer either way.&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;</div>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#f6f7f7" style="background:#f6f7f7;">
<tr>
<td align="center" style="padding:32px 0;">

  <!-- The paper. 600px, white, no border and no card: the design system asks
       for rules, not boxes, and a bordered card on grey is the shape every
       transactional email has, which is exactly why it reads as one. -->
  <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="width:100%;max-width:600px;background:#ffffff;">

    <!-- ── MASTHEAD ─────────────────────────────────────────────────────
         No black bar. White paper, the wordmark centred like the top of a
         printed page, one 12px tracked line of place under it, and a
         hairline. The mark carries real alt text, so a client that blocks
         images still reads "Mermade Market" where the mark would be. -->
    <tr>
      <td class="mm-pad" align="center" bgcolor="#ffffff" style="padding:34px 44px 22px;background:#ffffff;">
        <img src="__SITE__/email/wordmark.png" width="128" height="64" alt="Mermade Market" style="display:block;width:128px;height:64px;border:0;outline:none;text-decoration:none;">
        <div style="font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.22em;text-transform:uppercase;color:#767676;padding-top:12px;">Dana Point, California</div>
      </td>
    </tr>
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:0 44px;background:#ffffff;">
        <div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div>
      </td>
    </tr>

    <!-- ── THE OPENING PHOTOGRAPH ───────────────────────────────────────
         Full bleed, edge to edge. §4: "Full-bleed imagery is encouraged;
         text never is." The whole direction rests on this frame doing the
         emotional work so the type does not have to. hero.jpg is 2000x1125,
         drawn here at 600x338. Width as an attribute as well as a style,
         because Outlook's Word renderer ignores CSS width on an image, and
         a real height so the layout does not jump while it loads. -->
    <tr>
      <td bgcolor="#ffffff" style="padding:30px 0 0;font-size:0;line-height:0;background:#ffffff;">
        <img src="__SITE__/photos/hero.jpg" width="600" height="338" alt="The Community House floor under a ceiling of pale balloons and string lights, a shopper walking the aisle past a wall of handmade goods." style="display:block;width:100%;max-width:600px;height:auto;border:0;outline:none;text-decoration:none;">
      </td>
    </tr>

    <!-- ── EYEBROW, DISPLAY LINE, STANDFIRST ────────────────────────────
         The gold is the one accent and it does one job here: naming the
         section, the way it does on every page of the site. -->
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:40px 44px 0;background:#ffffff;">
        <div style="font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.20em;text-transform:uppercase;color:#bc9658;padding-bottom:16px;">Fall 2026 · Applications open</div>

        <div class="mm-display" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:36px;line-height:1.06;font-weight:600;letter-spacing:-0.022em;color:#171717;">Applications are open for November.</div>

        <div class="mm-stand" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:18px;line-height:1.55;font-weight:400;color:#5c5c5c;padding-top:18px;">Three days at the Community House, about a hundred makers, free at the door. One form covers both tracks, there is no fee to apply, and we answer either way.</div>
      </td>
    </tr>

    <!-- ── BODY, AT A COMFORTABLE MEASURE ───────────────────────────────
         512px at 16.5px lands around sixty characters a line. -->
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:22px 44px 0;background:#ffffff;">
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16.5px;line-height:1.68;color:#5c5c5c;">Everything on the floor was made by the person who applied. No resellers, no drop-shipping. A hundred makers is what fits in the room, so we look at everything and we say no a lot. If you have been meaning to apply, this is the window.</div>
      </td>
    </tr>

    <!-- ── THE ACTION, HIGH ─────────────────────────────────────────────
         A table with a bgcolor rather than a padded inline-block, because
         Outlook's Word renderer drops padding on an inline-block and the
         button arrives as a naked line of white text. The deadline sits
         directly under it, since that is the second thing the reader wants
         and the reason to act now. -->
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:30px 44px 0;background:#ffffff;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td bgcolor="#171717" align="center" style="background:#171717;">
              <a href="__SITE__/apply" style="display:block;padding:18px 40px;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:15px;font-weight:700;letter-spacing:0.09em;text-transform:uppercase;color:#ffffff;text-decoration:none;">Start your application</a>
            </td>
          </tr>
        </table>
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#767676;padding-top:13px;">Closes September 21, 11:59pm PT.</div>
      </td>
    </tr>

    <!-- ── TIMETABLE ────────────────────────────────────────────────────
         Design system §8: dated things as a ruled list with the date in its
         own column, so the eye runs down the dates rather than through the
         sentences. The date column is 118px, which holds "NOV 13-15" in
         Helvetica caps at 13px if Oswald never arrives. -->
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:44px 44px 0;background:#ffffff;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td width="1" style="padding-right:12px;white-space:nowrap;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.20em;text-transform:uppercase;color:#bc9658;">Dates that matter</td>
            <td style="width:100%;"><div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:14px 44px 0;background:#ffffff;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td class="mm-date" width="118" valign="top" style="width:118px;padding:12px 14px 12px 0;border-bottom:1px solid #dfe3e8;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.10em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 21</td>
            <td valign="top" style="padding:12px 0;border-bottom:1px solid #dfe3e8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#5c5c5c;">Applications close, 11:59pm PT</td>
          </tr>
          <tr>
            <td class="mm-date" valign="top" style="padding:12px 14px 12px 0;border-bottom:1px solid #dfe3e8;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.10em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 22-24</td>
            <td valign="top" style="padding:12px 0;border-bottom:1px solid #dfe3e8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#5c5c5c;">Decisions go out, either way</td>
          </tr>
          <tr>
            <td class="mm-date" valign="top" style="padding:12px 14px 12px 0;border-bottom:1px solid #dfe3e8;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.10em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 25</td>
            <td valign="top" style="padding:12px 0;border-bottom:1px solid #dfe3e8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#5c5c5c;">The makers are announced</td>
          </tr>
          <tr>
            <td class="mm-date" valign="top" style="padding:12px 14px 12px 0;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.10em;text-transform:uppercase;color:#171717;white-space:nowrap;">Nov 13-15</td>
            <td valign="top" style="padding:12px 0;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#171717;font-weight:500;">The show, at the Community House</td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- ── THE TWO TRACKS ───────────────────────────────────────────────
         Two plates of the same shape, side by side, the way a spread pairs
         pictures. Both frames are 900x600 files drawn at 246x164, so the
         pair reads as one decision rather than two crops.

         246 + 20 gutter + 246 = 512, which is the paper minus its 44px
         margins. A plain two-cell table, because Outlook's Word renderer
         ignores inline-block on a cell. At 320px each column lands near
         120px and the 14.5px text under it still sets three or four words
         to a line, so this never needs to stack. -->
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:46px 44px 0;background:#ffffff;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td width="1" style="padding-right:12px;white-space:nowrap;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.20em;text-transform:uppercase;color:#bc9658;">Two ways in</td>
            <td style="width:100%;"><div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:20px 44px 0;background:#ffffff;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td width="246" valign="top" style="width:246px;padding:0 10px 0 0;">
              <img src="__SITE__/photos/strip/mermade-23.jpg" width="246" height="164" alt="Handmade mugs and hanging clay ornaments arranged on a walnut shelf." style="display:block;width:100%;max-width:246px;height:auto;border:0;outline:none;text-decoration:none;">
              <div style="font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#171717;padding:14px 0 7px;">Inside</div>
              <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14.5px;line-height:1.6;color:#5c5c5c;">Consignment. Your work is on the floor all three days and you do not have to be. We merchandise it, sell it at one register, take 20%, and pay out after the show.</div>
            </td>
            <td width="246" valign="top" style="width:246px;padding:0 0 0 10px;">
              <img src="__SITE__/photos/strip/mermade-183.jpg" width="246" height="164" alt="A maker fastening a necklace for a shopper at her Charm Bar table under a white Mermade tent." style="display:block;width:100%;max-width:246px;height:auto;border:0;outline:none;text-decoration:none;">
              <div style="font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#171717;padding:14px 0 7px;">Outside</div>
              <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14.5px;line-height:1.6;color:#5c5c5c;">A tent we set up for you, for the day. You take your own payments and keep everything you sell. 0% commission.</div>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- ── THE CLOSE, AND THE ACTION AGAIN ──────────────────────────────
         The same button, second time. Not a second style: the same one, at
         the end, where a reader who scrolled the whole page arrives. -->
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:44px 44px 0;background:#ffffff;">
        <div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div>
      </td>
    </tr>
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:28px 44px 0;background:#ffffff;">
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16.5px;line-height:1.68;color:#5c5c5c;">The room is the Dana Point Community House, 24642 San Juan Avenue. Doors are free, all three days. Apply once and it covers both tracks.</div>
      </td>
    </tr>
    <tr>
      <td class="mm-pad" bgcolor="#ffffff" style="padding:24px 44px 48px;background:#ffffff;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td bgcolor="#171717" align="center" style="background:#171717;">
              <a href="__SITE__/apply" style="display:block;padding:18px 40px;font-family:Oswald,'Arial Narrow',Helvetica,Arial,sans-serif;font-size:15px;font-weight:700;letter-spacing:0.09em;text-transform:uppercase;color:#ffffff;text-decoration:none;">Start your application</a>
            </td>
          </tr>
        </table>
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#767676;padding-top:13px;">Or go to <a href="__SITE__/apply" style="color:#bc9658;text-decoration:underline;">mermademarket.com/apply</a></div>
      </td>
    </tr>

    <!-- ── COLOPHON ─────────────────────────────────────────────────────
         Quiet, on the shell grey, under a hairline. Explicit background and
         colour so an inverting client does not leave grey on grey. -->
    <tr>
      <td class="mm-pad" bgcolor="#f6f7f7" style="padding:24px 44px 30px;border-top:1px solid #dfe3e8;background:#f6f7f7;">
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:12.5px;line-height:1.7;color:#767676;">
          Mermade Market · Dana Point Community House, 24642 San Juan Avenue, Dana Point, CA 92629<br>
          You are on the maker list. About six emails a year.
          <a href="__SITE__/unsubscribe" style="color:#767676;text-decoration:underline;">Unsubscribe</a>.
        </div>
      </td>
    </tr>

  </table>

</td>
</tr>
</table>

</body>
</html>
`,
  },
  {
    id: 'concept-b-poster',
    title: "Mermade Market · Applications are open for November 13-15, 2026",
    html: `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>Mermade Market · Applications are open for November 13-15, 2026</title>

<!--
  ═══════════════════════════════════════════════════════════════════════
  CONCEPT B · PRINTED POSTER
  A letterpress broadside, mailed. Centred and symmetric, two inks, hairline
  rules doing the structure, and a 52px margin on every side so the sheet
  reads as paper rather than as a screen.

  ── THE TWO INKS ──────────────────────────────────────────────────────
  Ink      #171717  (--ink)      type
  Gold     #BC9658  (--accent)   RULES, ornament, and reversed type only.
  Gold is the second ink on the press, so it runs the rules the way a real
  two-colour job does. It is never set as type on the paper: #BC9658 on an
  off-white ground is 2.75:1, which fails even the 3:1 large-text floor. The
  one place gold becomes a letterform is the dark band at the foot of the
  sheet, where it runs 6.6:1 on #171717. That is the whole discipline of
  "gold as ink and not as a highlight".

  Paper    #FAFAF8  the sheet. Warm, not white. (globals.css --ad-bg)
  Ground   #EBEFED  the table the sheet lies on. (--dune)
  Body     #575651  6.7:1 on the paper
  Muted    #6E6D67  4.9:1 on the paper. Nothing smaller than 12px uses it.
  Hairline #DFE3E8  (--line), for interior structure the gold should not do

  ── TYPE, PER ROLE, AND WHAT HAPPENS WHEN GMAIL STRIPS THE WEBFONT ─────
  Gmail ignores the <link> below. Apple Mail, iOS Mail and Samsung Mail
  honour it. So every decision here is made for the fallback first, and the
  webfont is an improvement rather than a dependency.

  DISPLAY + LABELS   Oswald, 'Arial Narrow', 'Helvetica Neue', Helvetica,
                     Arial, sans-serif
    Used for: the letter-spaced month, the day numerals, every tracked caps
    label, and the buttons. NOT used for any headline sentence: Drew does
    not want all-caps headers that are not in our faces, and a 42px caps
    line becomes 42px of Helvetica capitals in Gmail. Caps here stops at
    label size (11-13px, tracked) plus the date plate, where the content is
    a month and three numerals, which are poster conventions in any face.

  PROSE              Figtree, -apple-system, BlinkMacSystemFont, 'Segoe UI',
                     Roboto, Helvetica, Arial, sans-serif
    Every sentence, sentence case, including the one display line. Figtree's
    fallbacks are ordinary grotesques, so the line degrades to something
    close rather than to something else.

  ── THE TYPOGRAPHIC RISK ──────────────────────────────────────────────
  The month is set one letter per table cell, eight cells at 12.5% each, so
  N O V E M B E R justifies to the exact measure of the sheet. The
  composition is table metric, not font metric: Oswald 700 and Helvetica
  Bold put different glyphs in the same eight slots and the line lands on
  the same two edges either way. CSS letter-spacing could not do this, and
  a letter-spaced line that loses its condensed face normally overruns the
  measure. This one cannot.
  It carries aria-hidden, and the same date is written out as a real
  sentence directly beneath it, so nothing is lost to a screen reader.

  ── EMAIL MECHANICS ───────────────────────────────────────────────────
  Tables and inline styles only. Outlook renders through Word, so: no
  flexbox, no grid, no float, no inline-block, percentage widths as
  attributes, align attributes for centring, and width AND height on every
  image. The <style> block below carries a phone media query only. It
  adjusts padding and two font sizes and nothing depends on it: strip it
  and the sheet still composes, because clients that ignore media queries
  render the 600px table and scale it.
  Backgrounds are painted on every cell that carries dark type, so a client
  inverting for dark mode cannot leave ink floating on its own black.
  ═══════════════════════════════════════════════════════════════════════
-->

<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=Figtree:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet">

<style>
  /* Phones only, and non-load-bearing. See the note above. */
  @media only screen and (max-width:480px) {
    .p-pad   { padding-left:26px !important; padding-right:26px !important; }
    .p-month { font-size:34px !important; }
    .p-num   { font-size:38px !important; }
    .p-lede  { font-size:30px !important; }
  }
</style>
</head>

<body style="margin:0;padding:0;background:#EBEFED;">

<!-- Inbox preview line, then blanks so the client does not read on into the sheet. -->
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">Indoor is consignment at 20%. Outdoor is your own tent at 0%. Both close September 21 at 11:59pm PT.&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;</div>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#EBEFED;">
<tr>
<td align="center" style="padding:34px 12px 40px;">

  <!-- ══ THE SHEET ══════════════════════════════════════════════════ -->
  <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" align="center" style="width:100%;max-width:600px;background:#FAFAF8;">

    <!-- Top of the sheet is paper. No bar, no band, no chrome. -->
    <tr><td style="height:46px;line-height:46px;font-size:0;">&nbsp;</td></tr>

    <!-- ── MASTHEAD ────────────────────────────────────────────────
         The wordmark is an image, which is the one piece of display
         typography here that is identical in Gmail and everywhere else.
         On a type-led sheet that is worth the request. Real alt text, so a
         client with images off still reads the name. -->
    <tr>
      <td align="center" class="p-pad" style="padding:0 52px;">
        <img src="__SITE__/email/wordmark.png" width="210" height="104" alt="Mermade Market" style="display:block;width:210px;height:104px;border:0;outline:none;text-decoration:none;">
      </td>
    </tr>

    <tr>
      <td align="center" class="p-pad" style="padding:20px 52px 0;">
        <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.24em;text-transform:uppercase;color:#6E6D67;line-height:1.4;">A juried market of independent makers</div>
      </td>
    </tr>

    <!-- The double rule. 2px ink over a 1px gold hairline, the way a
         broadside separates the masthead from the notice. -->
    <tr>
      <td class="p-pad" style="padding:22px 52px 0;">
        <div style="height:2px;background:#171717;font-size:0;line-height:0;">&nbsp;</div>
        <div style="height:4px;font-size:0;line-height:0;">&nbsp;</div>
        <div style="height:1px;background:#BC9658;font-size:0;line-height:0;">&nbsp;</div>
      </td>
    </tr>

    <!-- ── THE NOTICE ──────────────────────────────────────────────
         Sentence case, Figtree, centred. This is the only large sentence on
         the sheet and it is deliberately not in caps. -->
    <tr>
      <td align="center" class="p-pad" style="padding:40px 52px 0;">
        <div class="p-lede" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:40px;line-height:1.06;font-weight:600;letter-spacing:-0.022em;color:#171717;">Applications are open.</div>
      </td>
    </tr>

    <tr>
      <td align="center" class="p-pad" style="padding:16px 52px 0;">
        <table role="presentation" width="420" cellpadding="0" cellspacing="0" border="0" align="center" style="width:100%;max-width:420px;">
          <tr><td align="center" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:17px;line-height:1.55;color:#575651;">A hundred makers is what fits in the room. We read every application and answer either way, by September 25.</td></tr>
        </table>
      </td>
    </tr>

    <!-- ── THE DEADLINE STAMP ──────────────────────────────────────
         A hairline gold box, shrink-wrapped around the one date a maker has
         to act on. Centred, so it reads as a stamp on the sheet. -->
    <tr>
      <td align="center" class="p-pad" style="padding:28px 52px 0;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center">
          <tr>
            <td align="center" style="border:1px solid #BC9658;padding:14px 26px 16px;background:#FAFAF8;">
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.2em;text-transform:uppercase;color:#6E6D67;padding-bottom:7px;">Applications close</div>
              <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:19px;line-height:1.25;font-weight:600;color:#171717;">Monday, September 21, 11:59pm PT</div>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- ── PRIMARY CALL ────────────────────────────────────────────
         Full measure, solid ink, tracked caps at label weight. The address
         is printed under it in plain text, the way a poster prints the box
         office line, so the action survives a client that strips the href
         styling and so it can be read aloud. -->
    <tr>
      <td class="p-pad" style="padding:30px 52px 0;">
        <a href="__SITE__/apply" style="display:block;background:#171717;color:#FFFFFF;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px;font-weight:700;letter-spacing:0.14em;text-transform:uppercase;text-decoration:none;text-align:center;padding:19px 16px;">Apply to sell</a>
      </td>
    </tr>
    <tr>
      <td align="center" class="p-pad" style="padding:12px 52px 0;">
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:13px;line-height:1.5;color:#6E6D67;">mermademarket.com/apply</div>
      </td>
    </tr>

    <!-- ── ORNAMENT ────────────────────────────────────────────────
         Rule, printer's square, rule. Built from table cells and a
         background colour, so there is no glyph to lose and no character a
         client can turn into an emoji. -->
    <tr>
      <td class="p-pad" style="padding:36px 52px 0;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td valign="middle" style="font-size:0;line-height:0;"><div style="height:1px;background:#BC9658;font-size:0;line-height:0;">&nbsp;</div></td>
            <td width="30" valign="middle" align="center" style="font-size:0;line-height:0;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td width="7" height="7" style="width:7px;height:7px;background:#BC9658;font-size:0;line-height:0;">&nbsp;</td></tr></table>
            </td>
            <td valign="middle" style="font-size:0;line-height:0;"><div style="height:1px;background:#BC9658;font-size:0;line-height:0;">&nbsp;</div></td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- ── THE DATE PLATE ──────────────────────────────────────────
         The risk. Eight cells at 12.5%, one letter each, so the month
         justifies to the sheet in any typeface. aria-hidden, because the
         same date is a real sentence four rows down. -->
    <tr>
      <td align="center" class="p-pad" style="padding:30px 52px 0;">
        <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.24em;text-transform:uppercase;color:#6E6D67;">The show</div>
      </td>
    </tr>

    <tr>
      <td class="p-pad" style="padding:16px 52px 0;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" aria-hidden="true" style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;">
          <tr>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">N</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">O</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">V</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">E</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">M</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">B</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">E</td>
            <td width="12.5%" align="center" class="p-month" style="font-size:50px;line-height:1;font-weight:700;color:#171717;">R</td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- Three days, three columns, gold hairlines between them. Numerals
         hold their shape in every fallback face, which is why the loudest
         figures on the sheet are digits and not words. -->
    <tr>
      <td class="p-pad" style="padding:20px 52px 0;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" aria-hidden="true" style="border-top:1px solid #BC9658;border-bottom:1px solid #BC9658;">
          <tr>
            <td width="33.33%" align="center" valign="middle" style="padding:16px 4px 14px;">
              <div class="p-num" style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:50px;line-height:1;font-weight:700;color:#171717;">13</div>
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#6E6D67;padding-top:9px;">Friday</div>
            </td>
            <td width="33.33%" align="center" valign="middle" style="padding:16px 4px 14px;border-left:1px solid #BC9658;border-right:1px solid #BC9658;">
              <div class="p-num" style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:50px;line-height:1;font-weight:700;color:#171717;">14</div>
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#6E6D67;padding-top:9px;">Saturday</div>
            </td>
            <td width="33.33%" align="center" valign="middle" style="padding:16px 4px 14px;">
              <div class="p-num" style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:50px;line-height:1;font-weight:700;color:#171717;">15</div>
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#6E6D67;padding-top:9px;">Sunday</div>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <!-- The plate said in words. This is the row a screen reader gets, and
         the row that carries the year and the address. -->
    <tr>
      <td align="center" class="p-pad" style="padding:18px 52px 0;">
        <table role="presentation" width="440" cellpadding="0" cellspacing="0" border="0" align="center" style="width:100%;max-width:440px;">
          <tr><td align="center" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.55;color:#575651;">Friday to Sunday, November 13-15, 2026. Dana Point Community House, 24642 San Juan Avenue. Free to attend.</td></tr>
        </table>
      </td>
    </tr>

    <!-- ── THE ONE CUT ─────────────────────────────────────────────
         A single small plate, gold hairline, centred. Photography is the
         guest in this direction, not the host: at 240px it sits inside the
         measure like a woodcut on a broadside rather than taking the sheet
         over. Width and height are on the tag because Word ignores CSS
         sizing on an image, and the ratio matches the file. -->
    <tr>
      <td align="center" class="p-pad" style="padding:34px 52px 0;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center">
          <tr>
            <td style="padding:5px;border:1px solid #BC9658;background:#FAFAF8;font-size:0;line-height:0;">
              <img src="__SITE__/photos/room.jpg" width="240" height="136" alt="A shopper looking over a shelf of handmade goods under a string of warm bulbs" style="display:block;width:240px;height:136px;border:0;outline:none;text-decoration:none;background:#EBEFED;">
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr>
      <td align="center" class="p-pad" style="padding:14px 52px 0;">
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.5;font-style:italic;color:#6E6D67;">One register at the front means one bag at the end.</div>
      </td>
    </tr>

    <!-- ── TWO WAYS IN ─────────────────────────────────────────────
         The price-table shape from the design system, in a poster register:
         the rate lives in its own right-aligned column so 20% and 0% stack
         and compare, and the prose sits under the row rather than beside
         it, because two 220px columns of 14px text is a pamphlet and this
         is a sheet. -->
    <tr>
      <td class="p-pad" style="padding:38px 52px 0;">
        <div style="height:2px;background:#171717;font-size:0;line-height:0;">&nbsp;</div>
      </td>
    </tr>

    <tr>
      <td align="center" class="p-pad" style="padding:20px 52px 0;">
        <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.24em;text-transform:uppercase;color:#6E6D67;">Two ways in</div>
      </td>
    </tr>

    <tr>
      <td class="p-pad" style="padding:22px 52px 0;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">

          <!-- INDOOR -->
          <tr>
            <td valign="bottom" style="padding:0 10px 0 0;">
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:22px;font-weight:600;letter-spacing:0.12em;text-transform:uppercase;color:#171717;line-height:1.1;">Indoor</div>
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#6E6D67;padding-top:6px;">Consignment</div>
            </td>
            <td valign="bottom" align="right" width="120" style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:38px;line-height:1;font-weight:700;color:#171717;">20%</td>
          </tr>
          <tr>
            <td colspan="2" style="padding:12px 0 18px;border-bottom:1px solid #DFE3E8;">
              <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#575651;">We merchandise your work and sell it at one register at the front. You do not need to be there. We pay out after the show.</div>
            </td>
          </tr>

          <!-- OUTDOOR -->
          <tr>
            <td valign="bottom" style="padding:22px 10px 0 0;">
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:22px;font-weight:600;letter-spacing:0.12em;text-transform:uppercase;color:#171717;line-height:1.1;">Outdoor</div>
              <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#6E6D67;padding-top:6px;">Your own tent</div>
            </td>
            <td valign="bottom" align="right" width="120" style="padding-top:22px;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:38px;line-height:1;font-weight:700;color:#171717;">0%</td>
          </tr>
          <tr>
            <td colspan="2" style="padding:12px 0 0;">
              <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#575651;">A tent you run yourself for the day. Your own register, your own table, nothing owed on what you sell.</div>
            </td>
          </tr>

        </table>
      </td>
    </tr>

    <tr>
      <td class="p-pad" style="padding:20px 52px 0;">
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#6E6D67;">One form covers both. Tell us which you want, and apply for both if you cannot choose.</div>
      </td>
    </tr>

    <!-- ── DATES THAT MATTER ───────────────────────────────────────
         The timetable shape: the date in its own ruled column so the eye
         runs down the dates and not through the sentences. -->
    <tr>
      <td class="p-pad" style="padding:36px 52px 0;">
        <div style="height:1px;background:#BC9658;font-size:0;line-height:0;">&nbsp;</div>
      </td>
    </tr>

    <tr>
      <td class="p-pad" style="padding:20px 52px 0;">
        <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.24em;text-transform:uppercase;color:#6E6D67;">Dates that matter</div>
      </td>
    </tr>

    <tr>
      <td class="p-pad" style="padding:12px 52px 0;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td width="128" valign="top" style="padding:12px 14px 12px 0;border-bottom:1px solid #DFE3E8;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.14em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 21</td>
            <td valign="top" style="padding:12px 0;border-bottom:1px solid #DFE3E8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#575651;">Applications close, 11:59pm PT</td>
          </tr>
          <tr>
            <td width="128" valign="top" style="padding:12px 14px 12px 0;border-bottom:1px solid #DFE3E8;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.14em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 22-24</td>
            <td valign="top" style="padding:12px 0;border-bottom:1px solid #DFE3E8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#575651;">We read them and decide</td>
          </tr>
          <tr>
            <td width="128" valign="top" style="padding:12px 14px 12px 0;border-bottom:1px solid #DFE3E8;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.14em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 25</td>
            <td valign="top" style="padding:12px 0;border-bottom:1px solid #DFE3E8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#575651;">The list goes out</td>
          </tr>
          <tr>
            <td width="128" valign="top" style="padding:12px 14px 12px 0;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.14em;text-transform:uppercase;color:#171717;white-space:nowrap;">Nov 13-15</td>
            <td valign="top" style="padding:12px 0;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.45;color:#575651;">The show, at the Community House</td>
          </tr>
        </table>
      </td>
    </tr>

    <tr><td style="height:34px;line-height:34px;font-size:0;">&nbsp;</td></tr>

    <!-- ── THE FOOT OF THE SHEET ───────────────────────────────────
         The one ink block, and it is at the bottom, not the top: Drew asked
         for the black bar off the header. Here it is the press's closing
         panel, and it is the only place gold becomes a letterform, where it
         runs 6.6:1 on #171717 instead of 2.75:1 on paper. -->
    <tr>
      <td class="p-pad" style="padding:0 52px;">
        <div style="height:1px;background:#BC9658;font-size:0;line-height:0;">&nbsp;</div>
      </td>
    </tr>

    <tr>
      <td align="center" class="p-pad" style="padding:34px 52px 38px;background:#171717;">
        <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:13px;font-weight:600;letter-spacing:0.24em;text-transform:uppercase;color:#BC9658;padding-bottom:20px;">Apply before September 21</div>
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center">
          <tr>
            <td align="center" style="background:#FAFAF8;">
              <a href="__SITE__/apply" style="display:block;color:#171717;font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:15px;font-weight:700;letter-spacing:0.14em;text-transform:uppercase;text-decoration:none;padding:17px 34px;">Start your application</a>
            </td>
          </tr>
        </table>
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:#B7B5AE;padding-top:20px;">Have photographs of the work you would actually bring.</div>
      </td>
    </tr>

  </table>
  <!-- ══ END OF SHEET ═══════════════════════════════════════════════ -->

  <!-- The mailing label, printed off the poster and on the ground it lies
       on. #575651 runs 6.2:1 on #EBEFED. -->
  <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" align="center" style="width:100%;max-width:600px;">
    <tr>
      <td align="center" style="padding:26px 30px 0;">
        <div style="font-family:Oswald,'Arial Narrow','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:11.5px;font-weight:600;letter-spacing:0.2em;text-transform:uppercase;color:#575651;line-height:1.6;">Mermade Market &middot; Dana Point, California</div>
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:13px;line-height:1.6;color:#575651;padding-top:10px;">You are on this list because you asked to hear when applications open. About six emails a year.</div>
        <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:13px;line-height:1.6;padding-top:8px;"><a href="__SITE__/unsubscribe" style="color:#575651;text-decoration:underline;">Unsubscribe</a></div>
      </td>
    </tr>
  </table>

</td>
</tr>
</table>

</body>
</html>
`,
  },
  {
    id: 'concept-c-makers',
    title: "Mermade Market Fall 2026 · Applications are open",
    html: `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light only">
<title>Mermade Market Fall 2026 · Applications are open</title>

<!--
  CONCEPT C, THE MAKERS
  A hundred makers, three days, more than you can take in. One frame leads
  (mermade-183, a maker serving a shopper at the Charm Bar: the only strip
  frame with two people trading in it) and the rest support it in three bands
  of decreasing weight, with type set between the bands so the mosaic never
  flattens into a contact sheet.

  TYPE, AND WHAT HAPPENS WHEN THE WEB FONTS DO NOT LOAD.
  Google Fonts render in Apple Mail, iOS Mail and Samsung Mail. Gmail ignores
  the link entirely, so every size, weight and tracking value below is chosen
  to hold in the fallback, and nothing depends on the face arriving.

    Role                     Family     Fallback stack
    ----------------------------------------------------------------------
    Display line, lede,      Figtree    -apple-system, BlinkMacSystemFont,
    body, track copy,                   'Segoe UI', Roboto, Helvetica,
    timetable text,                     Arial, sans-serif
    stat figures                        (a plain grotesque either way, so the
                                         line degrades to something close)

    Eyebrow, section heads,  Oswald     'Helvetica Neue', Helvetica, Arial,
    stat labels, buttons,               sans-serif
    timetable dates                     (condensed becomes normal width, so
                                         no caps label runs long enough to
                                         wrap when it widens: the longest is
                                         "APPLICATIONS CLOSE" at 12px)

  The display line is SENTENCE CASE and Figtree, not Oswald caps. Drew: "I do
  not like all caps headers unless they use our fonts." Oswald arrives for
  one reader and not the next, and 40px of Helvetica capitals is not this
  brand at any size. Uppercase stops at label size, where the fallback still
  reads as a label. Design system §1 and §5.1 both set titles this way.

  No <style> block at all: every rule here is inline and every structure is a
  table, because Outlook renders through Word. Mobile needs no media query,
  since the 600px table is scaled to fit by every phone client.

  Colour is the theme's own (design system §2): ink #171717, body #5c5c5c,
  muted #767676, gold #bc9658, rule #dfe3e8, shell #f6f7f7, paper #ffffff.
  The masthead sits on white under a hairline. No dark bar at the top.

  Images: nine real frames plus the lead. Every one carries its width and
  height attributes at the file's true aspect ratio (strip portraits are
  400x600, strip landscapes 900x600), real alt text out of src/lib/content.ts,
  and display:block. Grid cells carry no whitespace between them, or Word
  opens a gap. mermade-213 sits at the very bottom, seven positions from
  mermade-214: same maker, same booth, never neighbours.
-->

<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=Figtree:wght@400;500;600&display=swap" rel="stylesheet">
</head>

<body style="margin:0;padding:0;background:#f6f7f7;">

<!-- Inbox preview line, then blanks so the client does not read the masthead alt out loud after it. -->
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">Fall 2026 applications close September 21 at 11:59pm PT. November 13 to 15 in Dana Point.&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;&#8203;&nbsp;</div>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f6f7f7;">
<tr>
<td align="center" style="padding:26px 0;">

<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;background:#ffffff;border-collapse:collapse;">

  <!-- MASTHEAD. White paper, hairline under it. -->
  <tr>
    <td style="padding:24px 32px 20px;border-bottom:1px solid #dfe3e8;">
      <img src="__SITE__/email/wordmark.png" width="140" height="70" alt="Mermade Market" style="display:block;width:140px;height:70px;border:0;outline:none;text-decoration:none;">
    </td>
  </tr>

  <!-- THE LEAD FRAME. Full bleed, 3:2, the only picture given the whole width. -->
  <tr>
    <td style="padding:0;font-size:0;line-height:0;">
      <img src="__SITE__/photos/strip/mermade-183.jpg" width="600" height="400" alt="A maker serving a shopper at the Charm Bar under a Mermade tent" style="display:block;width:100%;max-width:600px;height:auto;border:0;outline:none;text-decoration:none;background:#f6f7f7;">
    </td>
  </tr>

  <!-- EYEBROW, DISPLAY LINE, LEDE. -->
  <tr>
    <td style="padding:34px 32px 0;">
      <div style="font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:11px;font-weight:600;letter-spacing:0.18em;text-transform:uppercase;color:#bc9658;padding-bottom:14px;">Fall 2026 &middot; Applications are open</div>
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:40px;line-height:1.04;font-weight:600;letter-spacing:-0.021em;color:#171717;">A hundred makers is what fits in the room.</div>
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:17px;line-height:1.55;color:#5c5c5c;padding-top:16px;">November 13 to 15 at the Dana Point Community House, free to walk in all three days. If you made it yourself, the form is open now.</div>
    </td>
  </tr>

  <!-- THE ACTION, HIGH. Full width, black, one target. -->
  <tr>
    <td style="padding:24px 32px 0;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td align="center" bgcolor="#171717" style="background:#171717;">
            <a href="__SITE__/apply" style="display:block;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:15px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#ffffff;text-decoration:none;padding:18px 20px;">Apply to sell</a>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center" style="padding:11px 32px 0;">
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#5c5c5c;">Applications close September 21 at 11:59pm PT.</div>
    </td>
  </tr>

  <!-- THREE COUNTS, RULED. The figures do the arguing; the labels stay small. -->
  <tr>
    <td style="padding:26px 32px 0;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-top:1px solid #dfe3e8;border-bottom:1px solid #dfe3e8;">
        <tr>
          <td width="33%" valign="top" style="padding:16px 8px 16px 0;">
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:32px;line-height:1.05;font-weight:600;letter-spacing:-0.02em;color:#171717;">100</div>
            <div style="font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.13em;text-transform:uppercase;color:#767676;padding-top:6px;">Makers, give or take</div>
          </td>
          <td width="33%" valign="top" style="padding:16px 8px;">
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:32px;line-height:1.05;font-weight:600;letter-spacing:-0.02em;color:#171717;">3</div>
            <div style="font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.13em;text-transform:uppercase;color:#767676;padding-top:6px;">Days in November</div>
          </td>
          <td width="34%" valign="top" style="padding:16px 0 16px 8px;">
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:32px;line-height:1.05;font-weight:600;letter-spacing:-0.02em;color:#171717;">Free</div>
            <div style="font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.13em;text-transform:uppercase;color:#767676;padding-top:6px;">To walk in</div>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- SECTION HEAD. Gold caps, hairline running out from it. -->
  <tr>
    <td style="padding:28px 32px 16px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="1" style="padding-right:10px;white-space:nowrap;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.16em;text-transform:uppercase;color:#bc9658;">Last November, on the floor</td>
          <td style="font-size:0;line-height:0;"><div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div></td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- MOSAIC BAND ONE. Three portraits, 200x300 each, person / work / person.
       No whitespace between the cells or Word inserts a gap. -->
  <tr>
    <td style="padding:0;font-size:0;line-height:0;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;">
        <tr><td width="200" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-130.jpg" width="200" height="300" alt="A shopper walking the outdoor aisle between white Mermade tents" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td><td width="200" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-27.jpg" width="200" height="300" alt="Embroidered caps hung on horseshoe hooks" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td><td width="200" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-139.jpg" width="200" height="300" alt="A shopper looking over a shelf of goods under warm bulbs" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td></tr>
      </table>
    </td>
  </tr>

  <!-- MOSAIC BAND TWO. Two landscapes, 300x200. The shallow band is the beat
       between the tall rows, and it is what keeps this from reading as a
       contact sheet. -->
  <tr>
    <td style="padding:0;font-size:0;line-height:0;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;">
        <tr><td width="300" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-23.jpg" width="300" height="200" alt="Handmade mugs and hanging ornaments on a walnut shelf" style="display:block;width:300px;height:200px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td><td width="300" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-214.jpg" width="300" height="200" alt="A maker fastening a clasp for a customer" style="display:block;width:300px;height:200px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td></tr>
      </table>
    </td>
  </tr>

  <!-- TYPE, BETWEEN THE PICTURES. Set large enough to hold the page open
       rather than float as a caption. -->
  <tr>
    <td style="padding:30px 32px 30px;">
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:23px;line-height:1.3;font-weight:600;letter-spacing:-0.015em;color:#171717;">Everything on this floor was made by the person selling it.</div>
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#5c5c5c;padding-top:10px;">No resellers, no drop-shipping. We read every application and we answer either way.</div>
    </td>
  </tr>

  <!-- MOSAIC BAND THREE. Three portraits again, closing the wall. -->
  <tr>
    <td style="padding:0;font-size:0;line-height:0;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:600px;border-collapse:collapse;">
        <tr><td width="200" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-178.jpg" width="200" height="300" alt="A maker crocheting in her own tent, her bags hung behind her" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td><td width="200" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-123.jpg" width="200" height="300" alt="Handmade rag dolls on a rust linen cloth" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td><td width="200" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-180.jpg" width="200" height="300" alt="A candle maker beside her shelf under the Mermade tent" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td></tr>
      </table>
    </td>
  </tr>

  <!-- TWO WAYS IN. Type only, on purpose: after eight photographs the reader
       needs the terms, not another picture. -->
  <tr>
    <td style="padding:34px 32px 16px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="1" style="padding-right:10px;white-space:nowrap;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.16em;text-transform:uppercase;color:#bc9658;">Two ways in</td>
          <td style="font-size:0;line-height:0;"><div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:0 32px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="50%" valign="top" style="padding:0 14px 0 0;">
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:20px;line-height:1.2;font-weight:600;color:#171717;padding-bottom:8px;">Inside</div>
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#5c5c5c;">Consignment. We merchandise your work in the room and sell it at one register out front. You do not stand a booth and you do not have to be there. We keep 20% and pay out after the show.</div>
            <div style="padding-top:9px;"><a href="__SITE__/makers/indoor" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;color:#bc9658;text-decoration:underline;">The indoor deal</a></div>
          </td>
          <td width="50%" valign="top" style="padding:0 0 0 14px;">
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:20px;line-height:1.2;font-weight:600;color:#171717;padding-bottom:8px;">Outside</div>
            <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:#5c5c5c;">A tent for the day, and you run it. We put it up, you take your own payments and keep your own hours. We take 0% on your sales.</div>
            <div style="padding-top:9px;"><a href="__SITE__/makers/outdoor" style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;color:#bc9658;text-decoration:underline;">The outdoor deal</a></div>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- THE DATES, with the tenth frame beside them. mermade-213 lands here,
       three bands below mermade-214: same maker, same booth, kept apart. -->
  <tr>
    <td style="padding:34px 32px 16px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td width="1" style="padding-right:10px;white-space:nowrap;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.16em;text-transform:uppercase;color:#bc9658;">Dates that matter</td>
          <td style="font-size:0;line-height:0;"><div style="height:1px;background:#dfe3e8;line-height:1px;font-size:0;">&nbsp;</div></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:0 32px;">
      <table role="presentation" width="536" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:536px;border-collapse:collapse;">
        <tr>
          <td width="200" valign="top" style="padding:0;font-size:0;line-height:0;"><img src="__SITE__/photos/strip/mermade-213.jpg" width="200" height="300" alt="A jewellery booth laid out on linen risers" style="display:block;width:200px;height:300px;border:0;outline:none;text-decoration:none;background:#f6f7f7;"></td>
          <td width="336" valign="top" style="padding:0 0 0 24px;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td width="88" valign="top" style="padding:0 0 12px;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 21</td>
                <td valign="top" style="padding:0 0 12px;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.4;color:#5c5c5c;">Applications close, 11:59pm PT</td>
              </tr>
              <tr>
                <td width="88" valign="top" style="padding:12px 0;border-top:1px solid #dfe3e8;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 22-24</td>
                <td valign="top" style="padding:12px 0;border-top:1px solid #dfe3e8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.4;color:#5c5c5c;">We read them and decide</td>
              </tr>
              <tr>
                <td width="88" valign="top" style="padding:12px 0;border-top:1px solid #dfe3e8;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:#171717;white-space:nowrap;">Sep 25</td>
                <td valign="top" style="padding:12px 0;border-top:1px solid #dfe3e8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.4;color:#5c5c5c;">Makers announced</td>
              </tr>
              <tr>
                <td width="88" valign="top" style="padding:12px 0 0;border-top:1px solid #dfe3e8;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:12px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;color:#171717;white-space:nowrap;">Nov 13-15</td>
                <td valign="top" style="padding:12px 0 0;border-top:1px solid #dfe3e8;font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:15px;line-height:1.4;color:#171717;font-weight:600;">The show</td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>

  <!-- THE ACTION AGAIN, at the end of the scroll. -->
  <tr>
    <td style="padding:30px 32px 0;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td align="center" bgcolor="#171717" style="background:#171717;">
            <a href="__SITE__/apply" style="display:block;font-family:Oswald,'Helvetica Neue',Helvetica,Arial,sans-serif;font-size:15px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#ffffff;text-decoration:none;padding:18px 20px;">Start your application</a>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center" style="padding:11px 32px 30px;">
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.5;color:#5c5c5c;">One form, both tracks. <a href="__SITE__/apply" style="color:#bc9658;text-decoration:underline;">mermademarket.com/apply</a></div>
    </td>
  </tr>

  <!-- COLOPHON. -->
  <tr>
    <td style="padding:22px 32px 26px;border-top:1px solid #dfe3e8;background:#f6f7f7;">
      <div style="font-family:Figtree,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:12px;line-height:1.65;color:#767676;">
        Mermade Market &middot; Dana Point Community House, 24642 San Juan Avenue, Dana Point, California<br>
        <!-- Replace with the list's own merge tag before sending. A broadcast must carry one. -->
        <a href="{{unsubscribe_url}}" style="color:#767676;text-decoration:underline;">Unsubscribe</a>
      </div>
    </td>
  </tr>

</table>

</td>
</tr>
</table>

</body>
</html>
`,
  },
] as const
