/**
 * Turns the concept .html files into a TypeScript module.
 *
 * The concepts are whole email documents, written as files because that is
 * what an email is. They have to reach the preview route, which runs on
 * Vercel, where reading a file off disk means teaching the bundler to trace
 * it. A generated module has no such problem: it is imported like any other
 * source, so it cannot be missing at runtime.
 *
 * Re-run after editing any file in email/concepts/:
 *   npx tsx scripts/build-email-concepts.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const DIR = join(process.cwd(), 'src/server/modules/email/concepts')
const OUT = join(process.cwd(), 'src/server/modules/email/concepts.gen.ts')

/** Safe inside a template literal: the escape, the fence, the interpolation. */
const lit = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

const files = readdirSync(DIR).filter((f) => f.endsWith('.html')).sort()
const entries = files.map((f) => {
  /* The concept files carry the real absolute domain, which is right for an
     email: a mail client has no origin to be relative to. For the PREVIEW it
     is wrong, because the frame's CSP only admits the origin the admin is
     being viewed on, so a hardcoded domain renders every image broken on any
     host but production. Swapped for a token the preview fills in with
     siteUrl(), which is the same value the file would have hardcoded. */
  const html = readFileSync(join(DIR, f), 'utf8')
    .replaceAll('https://mermademarket.com', '__SITE__')
  const id = f.replace(/\.html$/, '')
  const title = /<title>([^<]*)<\/title>/i.exec(html)?.[1]?.trim() ?? id
  return `  {\n    id: '${id}',\n    title: ${JSON.stringify(title)},\n    html: \`${lit(html)}\`,\n  },`
})

writeFileSync(OUT, `/* GENERATED by scripts/build-email-concepts.ts. Do not edit.
   Source: src/server/modules/email/concepts/*.html */

export const emailConcepts = [
${entries.join('\n')}
] as const
`)
console.log(`concepts: ${files.length} written to concepts.gen.ts`)
